// Reference data from https://github.com/asilverthorn/suikoden_ref/blob/main/Suikoden2_enums.js

// Character attribute index for CHARACTERS.attrs:
// C: Cap, E: Helmet
// L: Light Armor, H: Heavy Armor, V: Vest, R: Robe
// S: Shield
// M: Male, F: Female, K: Kobold, W: Winger, N: Nobility, Y: Youth
// Z: Monster/Beast (cannot equip armor/accessories)

const GameData = {
  CHARACTERS: {
    1: { "name": "Riou", "attrs": ["C", "L", "M", "Y"] },
    2: { "name": "Flik", "attrs": ["C", "L", "S", "M"] },
    3: { "name": "Viktor", "attrs": ["C", "L", "M"] },
    4: { "name": "Viki", "attrs": ["C", "R", "F"] },
    5: { "name": "Sheena", "attrs": ["C", "L", "S", "M"] },
    6: { "name": "Clive", "attrs": ["C", "L", "M"] },
    7: { "name": "Hix", "attrs": ["C", "L", "S", "M"] },
    8: { "name": "Tengaar", "attrs": ["C", "R", "F"] },
    9: { "name": "Futch", "attrs": ["E", "L", "S", "M", "Y"] },
    10: { "name": "Humphrey", "attrs": ["E", "H", "M"] },
    11: { "name": "Georg", "attrs": ["C", "L", "M"] },
    12: { "name": "Valeria", "attrs": ["C", "L", "S", "F"] },
    13: { "name": "Pesmerga", "attrs": ["E", "H", "S", "M"] },
    14: { "name": "Lorelai", "attrs": ["E", "L", "F"] },
    15: { "name": "Shin", "attrs": ["C", "L", "M"] },
    16: { "name": "Rikimaru", "attrs": ["E", "L", "M"] },
    17: { "name": "Tomo", "attrs": ["C", "V", "F", "Y"] },
    18: { "name": "Nanami", "attrs": ["C", "V", "F"] },
    19: { "name": "Eilie", "attrs": ["C", "V", "F", "Y"] },
    20: { "name": "Rina", "attrs": ["C", "V", "F"] },
    21: { "name": "Bolgan", "attrs": ["E", "L", "M", "Y"] },
    22: { "name": "Tuta", "attrs": ["C", "R", "M", "Y"] },
    23: { "name": "Hanna", "attrs": ["E", "L", "S", "F"] },
    24: { "name": "Milie", "attrs": ["C", "V", "F", "Y"] },
    25: { "name": "Karen", "attrs": ["C", "V", "F"] },
    26: { "name": "Shiro", "attrs": ["Z"] },
    27: { "name": "Zamza", "attrs": ["C", "R", "M"] },
    28: { "name": "Gengen", "attrs": ["E", "L", "S", "K", "Y"] },
    29: { "name": "Gabotcha", "attrs": ["C", "L", "K", "Y"] },
    30: { "name": "Kinnison", "attrs": ["C", "L", "M"] },
    31: { "name": "Shilo", "attrs": ["C", "V", "M"] },
    32: { "name": "Miklotov", "attrs": ["E", "H", "M"] },
    33: { "name": "Camus", "attrs": ["E", "L", "S", "M"] },
    34: { "name": "Hauser", "attrs": ["E", "L", "M"] },
    35: { "name": "Freed Y", "attrs": ["E", "L", "S", "M"] },
    36: { "name": "Kahn", "attrs": ["E", "L", "M"] },
    37: { "name": "Amada", "attrs": ["C", "V", "M"] },
    38: { "name": "Tai Ho", "attrs": ["C", "V", "M"] },
    39: { "name": "Anita", "attrs": ["C", "L", "S", "F"] },
    40: { "name": "Bob", "attrs": ["C", "V", "M"] },
    41: { "name": "Meg", "attrs": ["C", "V", "F", "Y"] },
    42: { "name": "Gadget", "attrs": ["Z"] },
    43: { "name": "Ayda", "attrs": ["C", "V", "F", "Y"] },
    44: { "name": "Killey", "attrs": ["C", "L", "M"] },
    45: { "name": "Sierra", "attrs": ["C", "V", "F"] },
    46: { "name": "Oulan", "attrs": ["E", "L", "F"] },
    47: { "name": "Genshu", "attrs": ["C", "V", "M"] },
    48: { "name": "Mukumuku", "attrs": ["Z"] },
    49: { "name": "Abizboah", "attrs": ["Z"] },
    50: { "name": "Feather", "attrs": ["Z"] },
    51: { "name": "Badeaux", "attrs": ["E", "H", "M"] },
    52: { "name": "Tsai", "attrs": ["C", "V", "M"] },
    53: { "name": "Luc", "attrs": ["C", "R", "M", "Y"] },
    54: { "name": "Chaco", "attrs": ["C", "V", "W"] },
    55: { "name": "Nina", "attrs": ["C", "V", "F", "Y"] },
    56: { "name": "Sid", "attrs": ["C", "V", "W"] },
    57: { "name": "Yoshino", "attrs": ["C", "V", "F"] },
    58: { "name": "Gijimu", "attrs": ["E", "H", "M"] },
    59: { "name": "Koyu", "attrs": ["C", "L", "M", "Y"] },
    60: { "name": "Lo Wen", "attrs": ["E", "L", "F"] },
    62: { "name": "Sasuke", "attrs": ["C", "V", "M", "Y"] },
    63: { "name": "Mondo", "attrs": ["C", "V", "M"] },
    64: { "name": "Vincent", "attrs": ["C", "L", "S", "N"] },
    65: { "name": "Simone", "attrs": ["C", "L", "N"] },
    66: { "name": "Hai Yo", "attrs": ["C", "L", "M"] },
    67: { "name": "Stallion", "attrs": ["C", "L", "M"] },
    68: { "name": "Wakaba", "attrs": ["C", "V", "F"] },
    69: { "name": "Long Chan-Chan", "attrs": ["C", "V", "M"] },
    70: { "name": "Gantetsu", "attrs": ["C", "V", "M"] },
    71: { "name": "Hoi", "attrs": ["C", "L", "M"] },
    71: { "name": "Mazus", "attrs": ["C", "R", "M"] },
    72: { "name": "Siegfried", "attrs": ["Z"] },
    73: { "name": "Kasumi", "attrs": ["C", "V", "F"] },
    74: { "name": "Rulodia", "attrs": ["Z"] },
    75: { "name": "Makumaku", "attrs": ["Z"] },
    76: { "name": "Mikumiku", "attrs": ["Z"] },
    77: { "name": "Mekumeku", "attrs": ["Z"] },
    78: { "name": "MokuMoku", "attrs": ["Z"] },
    79: { "name": "Chuchara", "attrs": ["Z"] },
    80: { "name": "Jowy 1", "attrs": ["C", "L", "M"] },
    81: { "name": "Jowy 2", "attrs": ["C", "L", "M"] },
    82: { "name": "McDohl", "attrs": ["C", "L", "M"] },
    83: { "name": "Milie Sans Bonapart", "attrs": ["C", "V", "F", "Y"] },
    85: { "name": "Apple", "attrs": ["NP"] },
    86: { "name": "Templton", "attrs": ["NP"] },
    87: { "name": "Kiba", "attrs": ["NP"] },
    88: { "name": "Fitcher", "attrs": ["NP"] },
    89: { "name": "Shu", "attrs": ["NP"] },
    90: { "name": "Tetsu", "attrs": ["NP"] },
    91: { "name": "Leona", "attrs": ["NP"] },
    92: { "name": "Huan", "attrs": ["NP"] },
    93: { "name": "Jess", "attrs": ["NP"] },
    94: { "name": "Hilda", "attrs": ["NP"] },
    95: { "name": "Alex", "attrs": ["NP"] },
    96: { "name": "Emilia", "attrs": ["NP"] },
    97: { "name": "Tenkou", "attrs": ["NP"] },
    98: { "name": "Barbara", "attrs": ["NP"] },
    99: { "name": "Richmond", "attrs": ["NP"] },
    100: { "name": "Yam Koo", "attrs": ["NP"] },
    101: { "name": "Teresa", "attrs": ["NP"] },
    102: { "name": "Yuzu", "attrs": ["NP"] },
    103: { "name": "Taki", "attrs": ["NP"] },
    104: { "name": "Tony", "attrs": ["NP"] },
    105: { "name": "Adlai", "attrs": ["NP"] },
    106: { "name": "Gordon", "attrs": ["NP"] },
    107: { "name": "Hans", "attrs": ["NP"] },
    108: { "name": "Connell", "attrs": ["NP"] },
    109: { "name": "Lebrante", "attrs": ["NP"] },
    110: { "name": "Tessai", "attrs": ["NP"] },
    111: { "name": "Raura", "attrs": ["NP"] },
    112: { "name": "Annallee", "attrs": ["NP"] },
    113: { "name": "Pico", "attrs": ["NP"] },
    114: { "name": "Alberto", "attrs": ["NP"] },
    115: { "name": "Jude", "attrs": ["NP"] },
    116: { "name": "Jeanue", "attrs": ["NP"] },
    117: { "name": "Ridley", "attrs": ["NP"] },
    118: { "name": "Klaus", "attrs": ["NP"] },
    119: { "name": "Max", "attrs": ["NP"] },
    120: { "name": "Marlowe", "attrs": ["NP"] },
    121: { "name": "Gilbert", "attrs": ["NP"] },
    122: { "name": "Pilika 1", "attrs": ["NP"] },
    123: { "name": "Pilika 2", "attrs": ["NP"] },
    124: { "name": "Gremio", "attrs": ["NP"] },

  },

  
  ITEMS: { // use_cnt 0 to 9
    0: "None", 1: "Medicine", 2: "Mega Medicine", 3: "Antitoxin", 4: "Throat Drops", 5: "Needle",
    6: "Flaming Arrows", 7: "Dancing Flames", 8: "Fire Wall", 9: "Kindness Drops", 10: "Protect Mist",
    11: "Kindness Rain", 12: "Wind of Sleep", 13: "Healing Wind", 14: "The Shredding", 15: "Clay Guardian",
    16: "Revenge Earth", 17: "Canopy Defense", 18: "Angry Blow", 19: "Thunder Runner", 20: "Bolt of Wrath",
    21: "Stone of Power", 22: "Stone of Magic", 23: "Stone of Defense", 24: "Stone of Magic-Defense",
    25: "Stone of Dexterity", 26: "Stone of Speed", 27: "Stone of Luck", 28: "Dragon Censer",
    29: "Blinking Mirror", 30: "Sacrifical Jizo", 31: "Chick (Bath Set)", 32: "Drinking Set", 33: "Toy Boat",
    34: "Escape Talisman", 35: "Suiko Marp", 36: "Rag", 37: "Oily Rag", 38: "Rope", 39: "Flint Stone",
    40: "Flint Stone", 41: "Flour", 42: "Wooden Amulet", 43: "Healing Herb", 44: "Reference Letter",
    45: "Highland Uniform", 46: "Listening Hood?", 47: "Iron Hammer", 48: "Copper Hammer", 49: "Silver Hammer",
    50: "Gold Hammer", 51: "Round Plate", 52: "Triangle Plate", 53: "Square Plate", 54: "Clay",
    55: "Listening Crystal", 56: "Recipe #25", 57: "Recipe #26", 58: "Recipe #27", 59: "Recipe #28",
    60: "Recipe #29", 61: "Recipe #30", 62: "Recipe #31", 63: "Recipe #32", 64: "Recipe #33",
    65: "Recipe #34", 66: "Recipe #35", 67: "Recipe #36", 68: "Recipe #37", 69: "Recipe #38",
    70: "Recipe #39", 71: "Recipe #40", 72: "Two Packages", 73: "Leon's Letter", 74: "Entry Permit",
    75: "Bath Set", 76: "Sunglasses", 77: "Dog Whistle", 78: "Lubricating Oil", 79: "Rose Bouquet",
    80: "Secret Writings", 81: "Millet Dumplings", 82: "Leisure Set", 83: "Invincible Smile",
    84: "Sexy Wink", 85: "Cup of the Oath"
  },
  
  FARMING: { // use_cnt 48
    0: "None", 1: "Cabbage Seed", 2: "Potato Seed", 3: "Spinach Seed", 4: "Tomato Seed",
    5: "Chick", 6: "Piglet", 7: "Lamb", 8: "Calf"
  },
  
  TRADE: { // use_cnt 64
    0: "None", 1: "Defective Urn", 2: "Octopus Pot", 3: "Flower Vase", 4: "Wide Urn",
    5: "Blue Dragon Urn", 6: "Celadon Urn", 7: "Black Urn", 8: "Fine China", 9: "Persian Lamp",
    10: "Hex Doll", 11: "Japanese Dish", 12: "Chinese Dish", 13: "Peeing Boy", 14: "Bonsai Tree",
    15: "Knight Statue", 16: "Goddess Statue", 17: "Coral", 18: "Graffiti", 19: "Flower Painting",
    20: "Lover's Garden", 21: "Landscape Scroll", 22: "Beauties of Nature", 23: "Sugar", 24: "Salt",
    25: "Soy Sauce", 26: "Mayonnaise", 27: "Red Pepper", 28: "Candle", 29: "Fur", 30: "Flute",
    31: "Wooden Amulet", 32: "Native Costume", 33: "Holly Berry", 34: "Wine", 35: "Deer Antler",
    36: "Book", 37: "Musk", 38: "Crystal Ball", 39: "Pearl", 40: "Ancient Text", 41: "Gold Bar",
    42: "Karen Painting A", 43: "Karen Painting B", 44: "Trio Painting", 45: "Karen Statue A",
    46: "Karen Statue B", 47: "Karen Statue C", 48: "Nanami's Vase", 49: "Large Vase", 50: "Genkaku's Vase"
  },
  
  BASE_ITEM: { // use_cnt 80
    0: "None", 1: "Old book vol 1", 2: "Old book vol 2", 3: "Old book vol 3", 4: "Old book vol 4",
    5: "Old book vol 5", 6: "Old book vol 6", 7: "Old book vol 7", 8: "Old book vol 8", 9: "Old book vol 9",
    10: "Old book vol 10", 11: "Old book vol 11", 12: "Old book vol 12", 13: "Window Set 1", 14: "Window Set 2",
    15: "Window Set 3", 16: "Window Set 4", 17: "Window Set 5", 18: "Window Set 6", 19: "Window Set 7",
    20: "Sound Set 1", 21: "Sound Set 2", 22: "Sound Set 3", 23: "Sound Set 4", 24: "Sound Set 5",
    25: "Sound Set 6", 26: "Sound Set 7", 27: "Dragon Plans 1", 28: "Dragon Plans 2", 29: "Dragon Plans 3",
    30: "Dragon Plans 4", 31: "Unicorn Plans 1", 32: "Unicorn Plans 2", 33: "Unicorn Plans 3",
    34: "Unicorn Plans 4", 35: "Rabbit Plans 1", 36: "Rabbit Plans 2", 37: "Rabbit Plans 3",
    38: "Rabbit Plans 4", 39: "Turtle Plans 1", 40: "Turtle Plans 2", 41: "Turtle Plans 3",
    42: "Turtle Plans 4", 43: "Recipe#1", 44: "Recipe#2", 45: "Recipe#3", 46: "Recipe#4", 47: "Recipe#5",
    48: "Recipe#6", 49: "Recipe#7", 50: "Recipe#8", 51: "Recipe#9", 52: "Recipe#10", 53: "Recipe#11",
    54: "Recipe#12", 55: "Recipe#13", 56: "Recipe#14", 57: "Recipe#15", 58: "Recipe#16", 59: "Recipe#17",
    60: "Recipe#18", 61: "Recipe#19", 62: "Recipe#20", 63: "Recipe#21", 64: "Recipe#22", 65: "Recipe#23",
    66: "Recipe#24"
  },
  
  FOOD: { // use_cnt >= 99
    0: "None", 1: "Tamago-Yaki", 2: "Sweet Omelet", 3: "Adult Fried Egg", 4: "Fried Egg",
    5: "Egg Mayo Roll", 6: "Eggsplosive", 7: "Tomato Soup", 8: "Tomato Juice", 9: "Raw Tomato",
    10: "Tomato Miso Soup", 11: "Tomato Salad", 12: "Red Hot Tomatoes", 13: "Ohitashi",
    14: "Spinach Cake", 15: "Spinach Juice", 16: "Spinach Saute", 17: "Spinach Salad",
    18: "Spicy Stir Fry", 19: "Salad", 20: "Sweet Salad", 21: "Pickled Cabbage", 22: "Island Salad",
    23: "Green Salad", 24: "Veggie Stir Fry", 25: "Gyoza", 26: "Fruit Gyoza", 27: "Steamed Gyoza",
    28: "Fried Gyoza", 29: "Deep-Fried Gyoza", 30: "Szechuan Gyoza", 31: "Chowder",
    32: "Potato Pudding", 33: "Vichyssoise", 34: "Dark Chowder", 35: "Egg Soup", 36: "Gumbo",
    37: "BBQ Meat Bun", 38: "Sweet Bean Bun", 39: "Ginger Beef Bun", 40: "Ma Bo Bun",
    41: "Pirate's Bun", 42: "Pizza Bun", 43: "Buttered Clams", 44: "Clam Pudding",
    45: "Grilled Scallops", 46: "Steamed Abalone", 47: "Clam Mayonnaise", 48: "Mai Mai??",
    49: "Fish Fry", 50: "Fish Donuts", 51: "Deep-Fried Fish", 52: "Tatsuta Age", 53: "French Fries",
    54: "Fried Tacos", 55: "Ice Cream", 56: "Pudding", 57: "Nanami Ice", 58: "Soy Ice",
    59: "Fried Ice Cream", 60: "Red Pepper Ice", 61: "Quiche", 62: "Pineapple Rice", 63: "Egg Porridge",
    64: "Baked Mochi", 65: "Cream Quiche", 66: "Lasagna", 67: "Sandwich", 68: "French Toast",
    69: "Steak Sandwich", 70: "Teriyaki Sandwich", 71: "Veggie Sandwich", 72: "Spicy Sandwich",
    73: "Meat Pie", 74: "Cream Pie", 75: "Meringue Pie", 76: "Kobold Pie", 77: "Mayonnaise Pie",
    78: "Chili Pie", 79: "Simmered Fish", 80: "Simmered Carp", 81: "Tai-Chili Style", 82: "Sole",
    83: "Fish with Sauce", 84: "Blackened Sole", 85: "Fried Fish Balls", 86: "Sweet&Sour Fish",
    87: "Crab Cakes", 88: "Meatballs", 89: "Greasy Fish", 90: "Fiery Fish Balls", 91: "Sunomono",
    92: "Sour Shrimp", 93: "Nonpei Sunomono", 94: "Gourmet Sunomono", 95: "Weird Sunomono",
    96: "Cajun Shrimp", 97: "Cake", 98: "Short Cake", 99: "Nanami Cake", 100: "Black Cake",
    101: "Cheesecake", 102: "Fire Cake", 103: "Croquettes", 104: "Sweet Croquettes",
    105: "Eilie Croquettes", 106: "Black Croquettes", 107: "Cream Croquettes", 108: "Hot Croquettes",
    109: "Pasta", 110: "Kiddie Pasta", 111: "Pasta Parmesan", 112: "Downtown Pasta",
    113: "Pasta Salad", 114: "Chili Pasta", 115: "Tempura", 116: "Snack Tempura",
    117: "Real Tempura", 118: "Tempura-Don", 119: "Amazing Tempura", 120: "Spicy Tempura",
    121: "Grilled Fish", 122: "Broiled Eel", 123: "Salted Fish", 124: "Dried Fish",
    125: "Salmon Meunire", 126: "Grilled Red Fish", 127: "Gratin", 128: "Apple Gratin",
    129: "Salty Gratin", 130: "Crispy Gratin", 131: "Creamy Gratin", 132: "Chili Gratin",
    133: "Rice Omelet", 134: "Kid's Lunch", 135: "Salty Omelet", 136: "Soy Rice Omelet",
    137: "Mayo Rice Omelet", 138: "Red Pepper Rice", 139: "Fried Rice", 140: "Shrimp Pilaf",
    141: "Salty Fried Rice", 142: "Gunpowder Rice", 143: "Heavy Pilaf", 144: "Spicy Pilaf",
    145: "Pizza", 146: "Pancakes", 147: "Anchovy Pizza", 148: "Senbei", 149: "Okonomiyaki",
    150: "Spicy Pizza", 151: "Teriyaki", 152: "Sweet Teriyaki", 153: "Hot Spareribs",
    154: "Mild Teriyaki", 155: "Teri-Cream", 156: "BBQ-Bomb", 157: "Tonkatsu",
    158: "Meat and Potato", 159: "Ginger Pork", 160: "Soy Cutlet", 161: "Cream Cutlets",
    162: "Spicy Cutlets", 163: "Curry Rice", 164: "Kiddie Curry", 165: "Salty Curry",
    166: "Japanese Curry", 167: "Creamy Curry", 168: "Red Curry", 169: "Grilled Beef",
    170: "Sukiyaki", 171: "Grilled Tongue", 172: "Beef Rice Bowl", 173: "Meat Salad",
    174: "Chige Nabe", 175: "Ramen", 176: "Chinese Noodles", 177: "Salty Ramen",
    178: "Soy Sauce Ramen", 179: "Gourmet Ramen", 180: "Red Hot Ramen", 181: "Hamburger",
    182: "Sugar-Cured Meat", 183: "Kobold Burger", 184: "Japan Burger", 185: "Tinto Burger",
    186: "Surprise Burger", 187: "Obento", 188: "Ladie's Lunch", 189: "Rising Sun Bento",
    190: "Sashimi Bento", 191: "Diet Lunch", 192: "Shrimp Lunch", 193: "Sushi",
    194: "Chirashi-Zashi", 195: "Salty Rice Ball", 196: "Fancy Rice Ball", 197: "French Roll",
    198: "Tekka-don", 199: "Japanese Stew", 200: "Sweet Tofu", 201: "Bouillabaise",
    202: "Shabu Shabu", 203: "Dark Stew", 204: "Spicy Stew", 205: "Full Course",
    206: "Elf Course", 207: "Kobold Course", 208: "Rokkaku Course", 209: "Matilda Course",
    210: "Tinto Specialty", 211: "Genghis Khan", 212: "Fa Chu Chin", 213: "Coopa",
    214: "Genghis Stew", 215: "Cream Stew", 216: "Tom Yum Stew", 217: "Steak",
    218: "Sweet Steak", 219: "Beefsteak", 220: "Japanese Steak", 221: "Piccata",
    222: "Pepper Steak", 223: "Sashimi Combo", 224: "Queen of the Sea", 225: "Sea Treasure",
    226: "Ship Combo", 227: "Salad Combo", 228: "Spicy Sashimi", 229: "Special Stew",
    230: "Sweet Syrup", 231: "Adult Stew", 232: "Clear or Cream Soup", 233: "Mellow Stew",
    234: "Spicy Stew", 235: "Kaiseki Dinner", 236: "Candy House", 237: "Salt House",
    238: "Complete Kaiseki", 239: "Special Salad", 240: "Flaming Sea Special"
  },
  
  RUNES: { // use_cnt 32
    0: { "name": "None", "attrs": [] },
    1: { "name": "Fire Orb", "attrs": ["N", "Wep"] },
    2: { "name": "Rage Orb", "attrs": ["N", "Wep"] },
    3: { "name": "Water Orb", "attrs": ["N", "Wep"] },
    4: { "name": "Flowing Orb", "attrs": ["N", "Wep"] },
    5: { "name": "Wind Orb", "attrs": ["N", "Wep"] },
    6: { "name": "Cyclone Orb", "attrs": ["N", "Wep"] },
    7: { "name": "Earth Orb", "attrs": ["N", "Wep"] },
    8: { "name": "Mother Earth Orb", "attrs": ["N", "Wep"] },
    9: { "name": "Lightning Orb", "attrs": ["N", "Wep"] },
    10: { "name": "Thunder Orb", "attrs": ["N", "Wep"] },
    11: { "name": "Soul Eater", "attrs": ["82", "RH", "X"] },
    12: { "name": "Resurrection Orb", "attrs": ["N"] },
    13: { "name": "Bright Shield Orb", "attrs": ["1", "RH", "X"] },
    14: { "name": "Black Sword Orb", "attrs": ["80", "81", "RH", "X"] },
    15: { "name": "Blinking Orb", "attrs": ["N"] },
    16: { "name": "Darkness Orb", "attrs": ["N"] },
    17: { "name": "Blue Gate Orb", "attrs": ["N", "HR"] },
    18: { "name": "White Saint Orb", "attrs": ["72", "LH", "X"] },
    19: { "name": "Titan Orb", "attrs": ["3", "10", "11", "13", "16", "32", "34"] },
    20: { "name": "Viper Orb", "attrs": ["2", "5", "7", "23", "25", "33", "35", "64"] },
    21: { "name": "Great Hawk Orb", "attrs": ["30", "43", "67"] },
    22: { "name": "Lion Orb", "attrs": ["45", "46", "68", "69"] },
    23: { "name": "Kite Orb", "attrs": ["6", "8", "19", "20", "24", "29", "31", "41", "60", "62", "65"] },
    24: { "name": "Unicorn Orb", "attrs": ["9", "17", "37", "38", "52", "54", "56", "57"] },
    25: { "name": "Gozu Orb", "attrs": ["14", "58", "59"] },
    26: { "name": "Pixie Orb", "attrs": ["4", "53", "70", "71"] },
    27: { "name": "Banshee Orb", "attrs": ["N"] },
    28: { "name": "Sylph Orb", "attrs": ["N"] },
    29: { "name": "Chimera Orb", "attrs": ["N"] },
    30: { "name": "Nymph Orb", "attrs": ["N"] },
    31: { "name": "Dryad Orb", "attrs": ["N"] },
    39: { "name": "Gadget Orb", "attrs": ["41", "RH", "X"] },
    40: { "name": "Shrike Orb", "attrs": ["73", "HR", "X"] },
    41: { "name": "Falcon Orb", "attrs": ["12", "39", "RH", "X"] },
    42: { "name": "Mayfly Orb", "attrs": ["63", "HR", "X"] },
    43: { "name": "Swallow Orb", "attrs": ["47", "RH", "X"] },
    44: { "name": "Fire Breath Orb", "attrs": ["21", "RH", "X"] },
    45: { "name": "Groundhog Orb", "attrs": ["24", "LH", "X"] },
    46: { "name": "Fire Dragon Orb", "attrs": ["27", "RH", "X"] },
    47: { "name": "Shining Wind Orb", "attrs": ["50", "HR", "X"] },
    48: { "name": "Blue Drop Orb", "attrs": ["49", "74", "HR", "X"] },
    49: { "name": "White Tiger Orb", "attrs": ["68", "RH"] },
    50: { "name": "Howling Orb", "attrs": ["51", "LH", "X"] },
    51: { "name": "Spider Slay Orb", "attrs": ["15", "RH"] },
    52: { "name": "Angry Dragon Orb", "attrs": ["46", "LH", "X"] },
    53: { "name": "Twin Ring Orb", "attrs": ["25", "RH", "X"] },
    54: { "name": "Rabid Fang Orb", "attrs": ["40", "HR", "X"] },
    62: { "name": "Fortune Orb", "attrs": ["N"] },
    63: { "name": "Prosperity Orb", "attrs": ["N"] },
    64: { "name": "Champion's Orb", "attrs": ["N"] },
    65: { "name": "Double-Jab Orb", "attrs": ["N"] },
    66: { "name": "Killer Orb", "attrs": ["N"] },
    67: { "name": "Counter Orb", "attrs": ["N"] },
    68: { "name": "Spark Orb", "attrs": ["N"] },
    69: { "name": "Gale Orb", "attrs": ["N"] },
    70: { "name": "Sunbeam Orb", "attrs": ["N"] },
    71: { "name": "Phero Orb", "attrs": ["N"] },
    72: { "name": "Knight Orb", "attrs": ["N"] },
    73: { "name": "Wall Orb", "attrs": ["N"] },
    74: { "name": "Haziness Orb", "attrs": ["N"] },
    75: { "name": "Drain Orb", "attrs": ["N"] },
    76: { "name": "Barrier Orb", "attrs": ["N"] },
    77: { "name": "Balance Orb", "attrs": ["N"] },
    78: { "name": "Fire Sealing Orb", "attrs": ["N"] },
    79: { "name": "Skunk Orb", "attrs": ["N"] },
    80: { "name": "Firefly Orb", "attrs": ["N"] },
    81: { "name": "Medicine Orb", "attrs": ["N"] },
    82: { "name": "Double-Edged Orb", "attrs": ["N"] },
    83: { "name": "Wizard Orb", "attrs": ["N"] },
    84: { "name": "Warrior Orb", "attrs": ["N"] },
    85: { "name": "Waking Orb", "attrs": ["N"] },
    86: { "name": "Alertness Orb", "attrs": ["N"] },
    87: { "name": "Fury Orb", "attrs": ["N"] },
    88: { "name": "Violence Orb", "attrs": ["N"] },
    89: { "name": "Godspeed Orb", "attrs": ["67", "HR", "X"] },
    92: { "name": "Fire Lizard Orb", "attrs": ["N"] },
    93: { "name": "Magic Drain Orb", "attrs": ["N"] },
    94: { "name": "Hunter Orb", "attrs": ["Wep", "ExR"] },
    95: { "name": "Technique Orb", "attrs": ["Wep", "ExR"] },
    96: { "name": "Silence Orb", "attrs": ["Wep", "ExR"] },
    97: { "name": "Poison Orb", "attrs": ["Wep", "ExR"] },
    98: { "name": "Knockdown Orb", "attrs": ["Wep", "ExR"] },
    99: { "name": "Sleep Orb", "attrs": ["Wep", "ExR"] },
    100: { "name": "Friendship Orb", "attrs": ["Wep", "ExR"] },
    101: { "name": "Solitude Orb", "attrs": ["Wep", "ExR"] },
    102: { "name": "Kindness Orb", "attrs": ["Wep", "ExR"] },
    103: { "name": "Exertion Orb", "attrs": ["Wep", "ExR"] }
  },
  
  HELMET: { // use_cnt 16
    0: "None", 
    1: { "name": "Bandanna", "attrs": ["C"] },
    2: { "name": "Leather Hat", "attrs": ["C", "E"] },
    3: { "name": "Wind Feather Ornament", "attrs": ["C"] },
    4: { "name": "Pointed Hat", "attrs": ["C"] },
    5: { "name": "Circlet", "attrs": ["C", "E"] },
    6: { "name": "Half Helmet", "attrs": ["C", "E"] },
    7: { "name": "Headgear", "attrs": ["C"] },
    8: { "name": "Silver Hat", "attrs": ["C"] },
    9: { "name": "Full Helmet", "attrs": ["E"] },
    10: { "name": "Wind Hat", "attrs": ["C"] },
    11: { "name": "Flame Helmet", "attrs": ["E"] },
    12: { "name": "Horned Helmet", "attrs": ["E"] },
    85: { "name": "Mole Helmet", "attrs": ["C", "E"] },

  },

  
  ARMOR: { // use_cnt 16
    0: "None",
    13: { "name": "Robe", "attrs": ["L", "V", "R"] },
    14: { "name": "Tunic", "attrs": ["L", "V"] },
    15: { "name": "Fur Coat", "attrs": ["L", "H", "V"] },
    16: { "name": "Brass Armor", "attrs": ["L", "H"] },
    17: { "name": "Guard Robe", "attrs": ["L", "V", "R"] },
    18: { "name": "Karate Uniform", "attrs": ["L", "V"] },
    19: { "name": "Leather Armor", "attrs": ["L", "H"] },
    20: { "name": "Chain Mail", "attrs": ["L"] },
    21: { "name": "Ninja Suit", "attrs": ["L", "V"] },
    22: { "name": "Half Plate", "attrs": ["H"] },
    23: { "name": "Magic Robe", "attrs": ["L", "V", "R"] },
    24: { "name": "Thunder God Garb", "attrs": ["V"] },
    25: { "name": "Scale Mail", "attrs": ["L"] },
    26: { "name": "Dragon Armor", "attrs": ["L", "H"] },
    27: { "name": "Master Robe", "attrs": ["V", "R"] },
    28: { "name": "Full Plate", "attrs": ["H"] },
    29: { "name": "Taikyoku Wear", "attrs": ["V"] },
    30: { "name": "Master Garb", "attrs": ["L", "H"] },
    31: { "name": "Robe of Mist", "attrs": ["V", "R"] },
    32: { "name": "Earth Armor", "attrs": ["L", "H"] },
    33: { "name": "Dream Robe", "attrs": ["V"] },
    34: { "name": "Silver Armor", "attrs": ["L"] },
    35: { "name": "Knight Armor", "attrs": ["H"] },
    36: { "name": "Blood Armor", "attrs": ["L", "H"] },
    37: { "name": "Windspun Armor", "attrs": ["H"] },
    86: { "name": "Mole Suit", "attrs": ["L", "H", "V", "R"] },
  },

  
  SHIELD: { // use_cnt 16
    0: "None", 38: "Wooden Shield", 39: "Iron Shield", 40: "Kite Shield", 41: "Main-Gauche",
    42: "Silver Shield", 43: "Chaos Shield", 44: "Earth Shield", 87: "Mole Shield"
  },
  
  OTHER_EQUIP_GEAR: { // use_cnt 16
    0: "None", 45: "Wooden Shoes", 46: "Boots", 47: "Toe Shoes", 48: "Winged Boots",
    49: "Iron Boots", 50: "Gloves", 51: "Gauntlet", 52: "Silverlet", 53: "Power Gloves",
    54: "Goldlet", 55: "Cape", 56: "Leather Cape", 57: "Fur Cape", 58: "Cape of Darkness",
    59: "Crimson Cape", 60: "Collar", 61: "Heavy Collar", 62: "Silver Collar",
    63: "Gold Collar", 64: "Wing Ornament", 65: "Greaves", 66: "Shoulder Pads",
    67: "Cheeks Guards", 68: "Belt of Strength", 69: "Fire Emblem", 70: "Gold Emblem",
    71: "Blue Ribbon", 72: "Star Earrings", 73: "Sun Badge", 74: "Fish Badge",
    75: "Rose Brooch", 76: "Water Amulet", 77: "Thunder Amulet", 78: "Wind Amulet",
    79: "Guard Ring", 80: "Magic Ring", 81: "Speed Ring", 82: "Power Ring",
    83: "Skill Ring", 84: "Lucky Ring"
  },
  
  // Beast/Monster characters that cannot equip any armor or accessories
  BEASTS: [26, 42, 48, 49, 50, 72, 74, 75, 76, 77, 78, 79]
  // 42: Gadget, 48: Mukumuku, 49: Abizboah, 50: Feather, 72: Siegfried,
  // 74: Rulodia, 75: Makumaku, 76: Mikumiku, 77: Mekumeku, 78: Mokumoku, 79: Chuchara
};
